### ISSUE TITLE
Docker compose error

### ISSUE THREAD

**Issue by denisjoshua** [heimoshuiyu/whisper-fastapi#1]
Hi there, 
I have try to make a docker compose file in order to install the whisper-fastapi
but in the docker log I take: 
`Traceback (most recent call last):
  File "/app/whisper_fastapi.py", line 77, in <module>
    model = faster_whisper.WhisperModel(
  File "/usr/local/lib/python3.10/dist-packages/faster_whisper/transcribe.py", line 634, in __init__
    self.model = ctranslate2.models.Whisper(
RuntimeError: CUDA failed with error out of memory`

I have change the model to "tiny-in8"... but I take same error. 

Here is my docker-compose file: 
services:
  whisper:
    image: docker.io/heimoshuiyu/whisper-fastapi:latest
    container_name: whisper
    restart: unless-stopped
    ports:
      - "10300:3001"  #  porta per home assistant (wyoming protocol) 
      - "5000:5000"   #  porta per API call  
    volumes:
      - ./data:/root/.cache/huggingface
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    tmpfs: /bkp/docker/whisper/tmp
    environment:
      - PUID=1000                 # ID utente
      - PGID=1000                 # ID gruppo
        #- WHISPER_MODEL=large-v2    # Modello Whisper da utilizzare
      - WHISPER_MODEL=tiny-int8    # Modello Whisper da utilizzare
      - WHISPER_BEAM=1            # Opzionale, beam size
      - WHISPER_LANG=it           # Opzionale, lingua da utilizzare
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - OPENAI_API_KEY=1234567890abcd
      - OPENAI_LLM_MODEL=gpt-4o
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia        # Richiesta di GPU NVIDIA
              count: 1              # Numero di GPU richieste
              capabilities: ["gpu"]                # Capacità richieste
    security_opt:
      - label=disable

Can I have a little help please ? 
Thanks in advance 
Denis

**Comment by heimoshuiyu** [comment]
- PUID=1000 # ID utente
- PGID=1000 # ID gruppo
#- WHISPER_MODEL=large-v2 # Modello Whisper da utilizzare
- WHISPER_MODEL=tiny-int8 # Modello Whisper da utilizzare
- WHISPER_BEAM=1 # Opzionale, beam size
- WHISPER_LANG=it # Opzionale, lingua da utilizzare

this envs have no effect

there is a `start-docker.sh` file in this repo, you can refer to it and write your docker-compose file.

here is an example

```yaml
version: '3.8'

services:
  whisper-fastapi:
    image: docker.io/heimoshuiyu/whisper-fastapi:latest
    container_name: whisper-fastapi
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      -  OPENAI_BASE_URL=https://api.openai.com/v1
      - OPENAI_API_KEY=1234567890abcd
      - OPENAI_LLM_MODEL=gpt-4o
    volumes:
      - ./data:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    command: ["--model", "tiny"]
```
